sudo: required
services:
  - docker

before_install:
  - docker build -t brandaser/docker-react -f Dockerfile.dev .

script:
  - docker run brandaser/docker-react npm run test:ci

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "ducker"
  env: "Ducker-env"
  bucket_name: "elasticbeanstalk-us-east-2-843559400382"
  bucket_path: "ducker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
